global:
  scrape_interval: 15s  # How often Prometheus scrapes

scrape_configs:
  - job_name: 'nestjs'
    static_configs:
      - targets: ['nestjs-app:3000']  # The Docker service name and port of the NestJS app
