version: "3.8"
services:
  frontend:
    image: maryem1994/smartagri:front-1
    ports:
      - "8081:80"
    depends_on:
      - backend

  backend:
    image: maryem1994/smartagri:back-1
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET="1234567"
      - JWT_EXPIRES=1h
      - MONGO_URI=mongodb+srv://admin:admin@cluster0.p5aaq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
