apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ingress-nginx
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['smartagri-back.ingress-nginx.svc.cluster.local:3000']